#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace components::table {

    enum class table_constraint_type : uint8_t
    {
        PRIMARY_KEY,
        UNIQUE,
        CHECK,
        FOREIGN_KEY
    };

    struct table_constraint_t {
        table_constraint_type type;
        std::vector<std::string> columns;
        std::string check_expression; // only for CHECK (raw SQL text)
        // FK fields — only meaningful when type == FOREIGN_KEY:
        std::string ref_database;     // referenced table's database (empty = same as child)
        std::string ref_collection;   // referenced table name
        std::vector<std::string> ref_columns; // matching column names in referenced table
        std::string name;             // optional constraint name (autogenerated when empty)
        // FK semantic flags (PostgreSQL FKCONSTR_* alphabet) — defaults match SQL standard:
        char fk_matchtype{'s'};       // 's' SIMPLE / 'f' FULL / 'p' PARTIAL
        char fk_del_action{'a'};      // 'a' NO ACTION / 'r' RESTRICT / 'c' CASCADE / 'n' SET NULL / 'd' SET DEFAULT
        char fk_upd_action{'a'};      // same alphabet as fk_del_action
    };

} // namespace components::table
