FROM ubuntu:22.04 AS builder

ENV TZ=America/US
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONFAULTHANDLER=1

RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        build-essential \
        ninja-build \
        python3-pip \
        python3-venv \
        curl gnupg apt-transport-https \
        zlib1g && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN    pip3 install --no-cache-dir conan==2.30.0 "cmake<4" && \
       conan profile detect --force && \
       conan remote add otterbrix https://conan.otterbrix.com --allowed-packages "actor-zeta/*"

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

WORKDIR /app
COPY ./conanfile.py ./conanfile.py
COPY ./profiles ./profiles
RUN conan install . -pr:h profiles/asan -pr:b default --build=missing -of build/asan

COPY ./integration ./integration
COPY ./cmake ./cmake
COPY ./components ./components
COPY ./core ./core
COPY ./services ./services
COPY ./example ./example
COPY ./CMakeLists.txt ./CMakeLists.txt
COPY ./CMakePresets.json ./CMakePresets.json

RUN cmake --workflow --preset asan

# Multistage build is faster and resulting image will be smaller
FROM mcr.microsoft.com/dotnet/sdk:7.0-jammy

RUN apt-get update && \
    apt-get install -y libasan6 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /app ./

RUN cd integration/csharp && \
    dotnet restore ./src/Duckstax.Otterbrix/Duckstax.Otterbrix.csproj && \
    dotnet restore ./tests/Duckstax.Otterbrix.Tests/Duckstax.Otterbrix.Tests.csproj

RUN mkdir -p integration/csharp/src/Duckstax.Otterbrix/bin/Release/net7.0 && \
    mkdir -p integration/csharp/tests/Duckstax.Otterbrix.Tests/bin/Release/net7.0 && \
    mkdir -p integration/csharp/build && \
    cp ./build/asan/integration/c/libotterbrix.so ./integration/csharp/build/libotterbrix.so && \
    cp ./build/asan/integration/c/libotterbrix.so ./integration/csharp/src/Duckstax.Otterbrix/bin/Release/net7.0/libotterbrix.so && \
    cp ./build/asan/integration/c/libotterbrix.so ./integration/csharp/tests/Duckstax.Otterbrix.Tests/bin/Release/net7.0/libotterbrix.so

RUN cd integration/csharp && \
    export ASAN_LIB=$(find /usr/lib/ -name "libasan.so.*" | head -n 1) && \
    ASAN_OPTIONS=detect_leaks=0 LD_PRELOAD=$ASAN_LIB dotnet test -c Release
